### ISSUE TITLE
oldnumeric is depreciated as of  NumPy 1.8 and removed in 1.9

### ISSUE THREAD

**Issue by sq7lrx** [sq6jnx/sr0wx.py#37]
oldnumeric is no longer available in newer numpy distributions. 

```
$ python sr0wx.py 
Traceback (most recent call last):
  File "sr0wx.py", line 63, in <module>
    import lib.cw as cw
  File "/home/sq7lrx/Devel/sr0wx.py/lib/cw.py", line 19, in <module>
    import numpy.oldnumeric as Numeric
ImportError: No module named oldnumeric
```

**Comment by sq7lrx** [comment]
source: https://github.com/numpy/numpy/pull/3638

**Comment by sq6jnx** [comment]
numpy and oldnumeric removed in 9e7eb9ce61d4b704506d718f60ad47f816e4e4f9

**Comment by sq6jnx** [comment]
Thanks for this report.
